### ISSUE TITLE
What is io.read_dir = '/res/data/iamDB/words-Reading/' ?

### ISSUE THREAD

**Issue by vinson2233** [Nikolai10/scrabble-gan#10]
Just as the title said.
I have download 3 files.
One is the huge tgz file.
One is ascii word txt file, and the last one is the random_word.txt

The
```python
io.raw_dir = '/res/data/iamDB/words/'
```
is supposed to be the extracted `words.tgz` file right?(The one with around 800-mb in size) 

Then what is ` io.read_dir = '/res/data/iamDB/words-Reading/'  suppose to be?
Thanks

**Comment by Nikolai10** [comment]
Hello @vinson2233, 

please have a look at /src/dinterface/dinterface.py.
This should answer your questions.

Additional information can be found here: https://towardsdatascience.com/scrabblegan-adversarial-generation-of-handwritten-text-images-628f8edcfeed, see section "Load and prepare the dataset".

Good luck with your work!
