### ISSUE TITLE
Could I ask one question about the filter size?

### ISSUE THREAD

**Issue by rlgnswk** [Nikolai10/scrabble-gan#11]
Hello, Thank you for your great paper and code.

I just curious why the a size of filter is determined by 32x8192?
This is my first paper which is related with text generation field. 
I can not understand intuitively.

Thank you.

**Comment by Nikolai10** [comment]
Hello @rlgnswk, 

this is not my paper, rather a TF implementation of https://arxiv.org/pdf/2003.10557.pdf. 
You can find the official implementation at: https://github.com/amzn/convolutional-handwriting-gan.

Concerning your question: As far as I remember, this is simply a design decision. Please have a look at section 4.1: 

*"Each filter has a size of 32×8192. To generate one n-character word, we select and concatenate n of these filters (including repetitions,as with the letter ‘e’ in Figure 2), multiplying them with a 32 dimensional noise vector z1, resulting in an n×8192 matrix. Next, the latter matrix is reshaped into a 512×4×4n".*

So in general, you could try using a different dimension, e.g. 32x4096, which would result in a 256x4x4n matrix. However, this could potentially reduce the representational power (we want to learn meaningful character representations); similarly, higher dimensionality would come at a higher computational cost, with possibly no performance differences - I suggest you give it a try yourself ;)
