### ISSUE TITLE
train scrabbleGAN on arabic database

### ISSUE THREAD

**Issue by Tailor2019** [Nikolai10/scrabble-gan#12]
hello!
@Nikolai10 
Thank you so much for this software!
I'm trying to train this GAN on an arabic database but I don't arrive to determine this process it always returns me errors.
Please, can you give what modification to do for using the scrabble GAN For an arabic database?
I'm adding  for "scrabble_gan.gin"
io.char_vec ='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZأ ب ت ث ج ح خ د ذ ر ز س ش ص ض ط ظ ع غ ف ق ك ل م ن هـ و ي '
also I'm adding the image in the folder "words"
and the image .png and its transcription ".txt" in the folder  (1....10)

**Comment by Nikolai10** [comment]
Hello @Tailor2019, 

could you please be a little more specific about the errors you are experiencing?

In general, the steps required to extend the language model have been discussed [here](https://github.com/Nikolai10/scrabble-gan/issues/5). Note that you also would need to replace the random word list with an Arabic equivalent.

**Comment by Tailor2019** [comment]
Thanks @Nikolai10  a lot for your reply !
![1](https://user-images.githubusercontent.com/47376635/160659007-fa4554db-6a3f-4fc6-b29a-7ec4a3b6b2d6.png)

i'm using a random word list 
for this parameter "n_classes" it contains number of characters or what?
for arabic how can I prepare the random words (arbitrary words) or there is a rule to use?
can i train this code on both iam and arabic database in the same time ?
thanks helping me!

**Comment by Nikolai10** [comment]
Well, before starting to train your own model, you should make sure that your custom data preprocessing works as expected. This can be verified in section [Load and Preprocess Dataset](https://colab.research.google.com/drive/1-JxJsYbAM9W69nTxSKTp-gR3ofwv5SjM?usp=sharing):

```
train_dataset = load_prepare_data(in_dim, batch_size, read_dir, char_vec, bucket_size)

# retrieve random batch; analyze your data e.g.  
image_batch, label_batch = next(train_dataset)
print(image_batch.shape)
print(label_batch.shape)
```

Most probably you will have to spend some time adapting the code to your needs.

_for this parameter "n_classes" it contains number of characters or what?_
n_classes should equal len(char_vec)

_for arabic how can I prepare the random words (arbitrary words) or there is a rule to use?_ 
replace the [English word list](https://www.dropbox.com/s/o60ubzh3m163j0x/random_words.txt?dl=0) with an Arabic list; or, simply translate it.

_can i train this code on both iam and arabic database in the same time ?_
in theory you can, however, I believe having two separate models might be more effective.

**Comment by Tailor2019** [comment]
@Nikolai10 
Thanks a lot fo all your informations !
I am applying your advice I will inform you of the result as soon as possible

**Comment by Tailor2019** [comment]
Hello!
@Nikolai10 
I'm changing scrabble_gan.gin as here
`# I/O and data structure
io.base_path = '/content/scrabble-gan'
io.checkpoint_dir = '/res/out/big_ac_gan/training_checkpoints'
io.gen_imgs_dir = '/res/out/big_ac_gan/images/'
io.model_dir = '/res/out/big_ac_gan/model/'

# Dataset
io.input_dim = (32, 160, 1)
io.buf_size = 80377
io.n_classes = 31
io.seq_len = None
io.bucket_size = 10
io.raw_dir = '/res/data/iamDB/words/'
io.read_dir = '/res/data/iamDB/words-Reading/'
io.char_vec ='أ ب ت ث ج ح خ د ذ ر ز س ش ص ض ط ظ ع غ ف ق ك ل م ن هـ و ي مارث'`
my prototype is 
![2](https://user-images.githubusercontent.com/47376635/161027193-e0e94e66-cc54-4b83-a0d3-f1495ba6fbac.png)
but it returns me this error:
![1](https://user-images.githubusercontent.com/47376635/161027349-069c4330-fd57-4222-8be9-e8697c040a02.png)
please can you help me solving this problem.
THANKS in advance!

**Comment by Nikolai10** [comment]
Hello @Tailor2019, 

please make sure that char_vec contains all Arabic characters represented in your word list.

Minimal error example:
```
# ValueError: substring not found
char_vector = 'أ ب ت ث ج ح خ د ذ ر ز س ش ص ض ط ظ ع غ ف ق ك ل م ن هـ و ي مارث'
word = 'قطّة (ج) قطط'
print([char_vector.index(char) for char in word])
```

Successful example:
```
# prints [0, 20, 19, 14]
char_vector = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
word = 'auto'
print([char_vector.index(char) for char in word])
```

**Comment by Tailor2019** [comment]
@Nikolai10 
thanks a lot for your help !
I'm doing all the requested (char vector modification; database preparation..)
when it arrive to the training 
it returns this error:
![1](https://user-images.githubusercontent.com/47376635/161320722-a924b190-d748-431d-bdc1-422be06e887d.png)
Please help me to solve this.
Thanks in advance!

**Comment by Nikolai10** [comment]
it still seems like your data preprocessing is incorrect. Have you checked that https://github.com/Nikolai10/scrabble-gan/issues/12#issuecomment-1082212890 works?

**Comment by Tailor2019** [comment]
Hello thanks @Nikolai10 !
this session runs with success
`# convert IAM Handwriting dataset (words) to GAN format
if not os.path.exists(read_dir):
  print('converting iamDB-Dataset to GAN format...')
  init_reading(raw_dir, read_dir, in_dim, bucket_size)
  print(bucket_size)
# load random words into memory (used for word generation by G)
random_words = load_random_word_list(read_dir, bucket_size, char_vec)

# load and preprocess dataset (python generator)
train_dataset = load_prepare_data(in_dim, batch_size, read_dir, char_vec, bucket_size)`
but tis part 
`#(************************/////////////////////////*****************************)
train_dataset = load_prepare_data(in_dim, batch_size, read_dir, char_vec, bucket_size)

# retrieve random batch; analyze your data e.g.  
image_batch, label_batch = next(train_dataset)
print(image_batch.shape)
print(label_batch.shape)`
returns me this error:
![1](https://user-images.githubusercontent.com/47376635/161376135-77c3dbaf-309c-4137-92d1-cff4461eadf8.png)
Please how can i resolve this problem?
if it is demands that i publish my prototype I can do that 
Thanks a lot in advance!

**Comment by Nikolai10** [comment]
Hello, 

feel free to create a Google Colab that allows for reproducing the error. Please make sure that you upload your resource folder e.g. to Google Drive such that it can be mounted (a subset of your training data is sufficient).

**Comment by zaghdoud2019** [comment]
thank you for your generosity in responding.I make all the requests and I resolve the problem of coding and decoding for Arabic character.But When I make this 
![image](https://user-images.githubusercontent.com/55888103/161430233-e57a69ed-4360-4bab-9f95-81ceb9a2e804.png)
it gives me this mistake
![image](https://user-images.githubusercontent.com/55888103/161430531-1e6f573a-bcff-4275-85f1-7d2138b5d49a.png)
and when I try to modify with:
image_batch = np.array(image_batch).astype(object)
label_batch = np.array(label_batch).astype(object)
i have this mistake:
![image](https://user-images.githubusercontent.com/55888103/161430694-ee29005f-4690-4c56-bfef-e7494108e582.png)
Please help.

**Comment by Tailor2019** [comment]
Hello,
@Nikolai10 
This is my prototype 👍 
i'm using the same image 5 times (this is the image that I used 
![a01-000u-00-00](https://user-images.githubusercontent.com/47376635/161497511-bbdb484d-326c-41c0-ae88-96e8cf4d9222.png)
for the random_words.txt I'm using these words!:
أ
أ
أأ
علي
عام
مارث
مارثمارث
مارثمارثمارثمارث
مارثمارثمارثمارثمارثمارث




for the  words.txt file is as following:
`a01-000u-00-00  مارث
a01-000u-00-01 مارث
a01-000u-00-02 مارث
a01-000u-00-03 مارث
a01-000u-00-04 مارث
`

[data.zip](https://github.com/Nikolai10/scrabble-gan/files/8407664/data.zip)
for the "scrabble_gan.gin" I only changing:
#io.char_vec ='أ ب ت ث ج ح خ د ذ ر ز س ش ص ض ط ظ ع غ ف ق ك ل م ن هـ و ي ما عا علي ثما '
#io.n_classes = 32
for this parameter 👍 
io.input_dim = (32, 160, 1) I don't change it because when  i put the real dimension of my image (449*119) it returns me 
the error that it don't support this dimension
I trying to download the project and mount it and running (!python main.py) also I'm using your colab notebook 
but the same error that I mentioned before occurs
![1](https://user-images.githubusercontent.com/47376635/161500131-c0dae8b4-e46f-4b99-9180-f4944fb08d87.png)
Please can you give what is warning for my prototype to turn it correctly on scrabble-gan.
Thanks in advance

**Comment by zaghdoud2019** [comment]
How reshape the array in the folowing instructions :
image_batch = image_batch.reshape(-1, h, int((h / 2) * random_bucket_idx), c)
As long as random_bucket_idx is random and each time has a new value.
Thanks in advance

**Comment by Nikolai10** [comment]
Hello @Tailor2019, could you please share a copy of your modified Google Colab? This would ease the process.

Concerning the image dimension: all images have to be reshaped to match the aspect ratio of each character: (height: 32 px, width: 16 px). E.g. a word of transcription length 10 has shape (32,160) px.

**Comment by Tailor2019** [comment]
@Nikolai10 
Thanks a lot for your reply 
excuse me for the link it demands my autorization this is aan accessible link without autorization 
https://colab.research.google.com/drive/15FfzDKWL320D-TCnZ96Crg7yPVCaerbr?usp=sharing

**Comment by Nikolai10** [comment]
Hello @Tailor2019, 

in your specific example, you need to adjust [convert_to_gan_reading_format_save()](https://github.com/Nikolai10/scrabble-gan/blob/master/src/dinterface/iam_handwriting_db.py#L36) likeso:

```
# (2) get file transcriptions (stored in words.txt)
transcription_file = input_dir.rstrip('/') + '.txt'
transcriptions = {}

with open(transcription_file, 'r', encoding="utf8") as fi:
    for line in fi:
        if not line.startswith('#'):
            labels = line.split()
            file_nm = labels[0] + '.png'

            transcription = labels[-1]
            transcriptions[file_nm] = transcription.strip()

print('size of iamDB words: {}'.format(len(transcriptions)))
```

then
```
# convert IAM Handwriting dataset (words) to GAN format
if not os.path.exists(read_dir):
    print('converting iamDB-Dataset to GAN format...')
    init_reading(raw_dir, read_dir, in_dim, bucket_size)
    print(bucket_size)
# load random words into memory (used for word generation by G)
random_words = load_random_word_list(read_dir, bucket_size, char_vec)

# load and preprocess dataset (python generator)
train_dataset = load_prepare_data(in_dim, batch_size, read_dir, char_vec, bucket_size)
```

should yield the following output:

> converting iamDB-Dataset to GAN format...
> convert iamDB words to GAN-Reading task...
> 
> size of iamDB words: 5
> /content/scrabble-gan/res/data/iamDB/words/a01/a01-000u/a01-000u-00-01.png
> /content/scrabble-gan/res/data/iamDB/words-Reading/4/
> /content/scrabble-gan/res/data/iamDB/words/a01/a01-000u/a01-000u-00-04.png
> /content/scrabble-gan/res/data/iamDB/words-Reading/4/
> /content/scrabble-gan/res/data/iamDB/words/a01/a01-000u/a01-000u-00-03.png
> /content/scrabble-gan/res/data/iamDB/words-Reading/4/
> /content/scrabble-gan/res/data/iamDB/words/a01/a01-000u/a01-000u-00-00.png
> /content/scrabble-gan/res/data/iamDB/words-Reading/4/
> /content/scrabble-gan/res/data/iamDB/words/a01/a01-000u/a01-000u-00-02.png
> /content/scrabble-gan/res/data/iamDB/words-Reading/4/
> size of valid iamDB words: 5
> Counter({4: 5})
> 10

**Please note:** in your specific example, only bucket 4 should contain images + corresponding transcripts.

As a sanity check:

```
image_batch, label_batch = next(train_dataset)
print(image_batch.shape)
print(label_batch.shape)
```

should yield

> (64, 32, 64, 1)
> (64, 4)

**Comment by Tailor2019** [comment]
Hello!
@Nikolai10 
I resolved the problem described above :
![1](https://user-images.githubusercontent.com/47376635/162616731-9b9da9cb-b620-4221-9ef0-4e667533d885.png)
but it returns me this error 

![1](https://user-images.githubusercontent.com/47376635/162616800-a51daa2e-4caf-461c-8251-9278e8f58abe.png)
can you help me please resolving this problem.
thanks in advance

**Comment by HananAbdulla** [comment]
Hello @[Tailor2019](https://github.com/Tailor2019)

How did you adjust the model for Arabic handwriting generation?
could you help me ?

Thanks..
