### ISSUE TITLE
Problem in image_batch array

### ISSUE THREAD

**Issue by HananAbdulla** [Nikolai10/scrabble-gan#16]
Hello @Nikolai10 
I changed the batch_size = 32
Then I got the following error, when training the model.

![Picture3](https://user-images.githubusercontent.com/16627947/166512987-4f9d5020-9507-4610-80ef-b2d78367b687.png)

Could you help me to resolve it?

Thanks..

**Comment by Nikolai10** [comment]
Hello @HananAbdulla, 

I am unable to reproduce the error; please have a look at https://colab.research.google.com/drive/1-JxJsYbAM9W69nTxSKTp-gR3ofwv5SjM?usp=sharing. 

I noticed that in the demo version, the default batch size is 32 as well.
Please make sure that the data preprocessing works as expected.
