### ISSUE TITLE
ValueError: Custom>spectral_norm has already been registered to <function spectral_norm at 0x000001765DB03DC0>

### ISSUE THREAD

**Issue by DeccanKing1** [Nikolai10/scrabble-gan#4]
After making all changes mentioned in readme file, i am getting an following error.

ValueError: Custom>spectral_norm has already been registered to <function spectral_norm at 0x000001765DB03DC0>

What is it related to? There is no enough mention of this error on internet hence raising the issue.

Detailed error:

runfile('C:/scrabble-gan-master/src/main.py', wdir='C:/scrabble-gan-master/src')
Reloaded modules: src, src.bigacgan, src.bigacgan.arch_ops, src.bigacgan.data_utils, src.bigacgan.resnet_ops, src.bigacgan.net_architecture, src.bigacgan.net_loss, src.dinterface, src.dinterface.iam_handwriting_db, src.dinterface.dinterface
Traceback (most recent call last):

  File "C:\scrabble-gan-master\src\main.py", line 17, in <module>
    from src.bigacgan.arch_ops import spectral_norm

  File "C:\scrabble-gan-master\src\bigacgan\arch_ops.py", line 99, in <module>
    def spectral_norm(w, power_iteration=1):

  File "C:\tools\Anaconda3\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 152, in decorator
    raise ValueError(

ValueError: Custom>spectral_norm has already been registered to <function spectral_norm at 0x000001765DB03DC0>

A bit about my system and python environment: Training on CPU

Python Environment:  I use Tensorflow '2.1.0'

System:processor 'AMD64', uname_result(system='Windows', node='nm-eros', release='10', version='10.0.18362', machine='AMD64', processor='Intel64 Family 6 Model 142 Stepping 12, GenuineIntel'),  'Intel64 Family 6 Model 142 Stepping 12, GenuineIntel'

**Comment by Nikolai10** [comment]
Hello @DeccanKing1, 

as a good practice, you always should include some information about your system. E.g. use the TensorFlow issue template: https://github.com/tensorflow/tensorflow/blob/master/ISSUE_TEMPLATE.md.

As a quick fix, you might want to set `shared_specs.kernel_reg = None` in the scrabble_gan.gin file. Then it should become much easier to "dig deeper".

**Comment by DeccanKing1** [comment]
@Nikolai10 Thank you very much for prompt reply. I updated issue with system and tensorflow information.

Eventhough when I set shared_specs.kernel_reg = None, I get an same error. Major doubt I had was, is this related to tensorflow or something else?

**Comment by Nikolai10** [comment]
Hello @DeccanKing1, 

the idea here was to integrate spectral normalization similar to https://github.com/taki0112/Spectral_Normalization-Tensorflow. In my work, you can find the corresponding implementation in /src/bigacgan/arch_ops.py.

So, if you set `shared_specs.kernel_reg = None`, this method will not get called at all. Consequently, it is not possible to get the same error message. Of course - you have to retrain your model under these new conditions.

**Comment by DeccanKing1** [comment]
@Nikolai10 Thank you very much. it worked to the further step where model is building. One more thing I wanted to ask about the structure of output directory in res folder.  I am confused with the name bucket. Do I have to make folders named buckets or is it something that I have to extract one of the data sources file from IAM DB there?

**Comment by Nikolai10** [comment]
@DeccanKing1 I have used the term bucket only as a metaphor to distinguish words of different lengths.

There is no need for manual work, everything is generated automatically. Please have a look at the method  convert_to_gan_reading_format_save() in dinterface/iam_handwriting_db.py for more details.

**Comment by patilanup1616** [comment]
> @DeccanKing1 I have used the term bucket only as a metaphor to distinguish words of different lengths.
> 
> There is no need for manual work, everything is generated automatically. Please have a look at the method convert_to_gan_reading_format_save() in dinterface/iam_handwriting_db.py for more details.

The reason I asked question about output directory is because although after creating the file structure mentioned in repository I get an error as 

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/scrabG/scrabble-gan/res/data/iamDB/words-Reading/1/' which is telling it could not find the path to store generated data in output directory which I have mentioned correctly. If try to create the folder manually like number named 1,2 ,3, I would get a same error, just path in the error would have the next number at the last.

**Comment by DeccanKing1** [comment]
> > @DeccanKing1 I have used the term bucket only as a metaphor to distinguish words of different lengths.
> > There is no need for manual work, everything is generated automatically. Please have a look at the method convert_to_gan_reading_format_save() in dinterface/iam_handwriting_db.py for more details.
> 
> The reason I asked question about output directory is because although after creating the file structure mentioned in repository I get an error as
> 
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/scrabG/scrabble-gan/res/data/iamDB/words-Reading/1/' which is telling it could not find the path to store generated data in output directory which I have mentioned correctly. If try to create the folder manually like number named 1,2 ,3, I would get a same error, just path in the error would have the next number at the last.

this got resolved, issue was relative address was not getting read properly in function.

**Comment by Nikolai10** [comment]
@DeccanKing1 please open a new issue.
