### ISSUE TITLE
Targeted output generation

### ISSUE THREAD

**Issue by DeccanKing1** [Nikolai10/scrabble-gan#5]
After training the model, if I have to generate some other characters and numbers from other language, I have to include these letters in file words_list.txt but will I have to train all the model for these characters again or should I just run some specific part of the code?

**Comment by loafenzy** [comment]
> After training the model, if I have to generate some other characters and numbers from other language, I have to include these letters in file words_list.txt but will I have to train all the model for these characters again or should I just run some specific part of the code?

Did you find a solution for this?

**Comment by Nikolai10** [comment]
Hello @DeccanKing1 @loafenzy, 

to extend the “language model” to additional characters, you need to:

1. update `char_vec` and `n_classes` in [scrabble_gan.gin](https://github.com/Nikolai10/scrabble-gan/blob/master/src/scrabble_gan.gin) as required; an example on how words are subsequently encoded is given in [load_random_word_list()](https://github.com/Nikolai10/scrabble-gan/blob/master/src/bigacgan/data_utils.py#L312).
2. provide additional training data.
3. retrain whole model.
