### ISSUE TITLE
How to generate the words provided?

### ISSUE THREAD

**Issue by DeccanKing1** [Nikolai10/scrabble-gan#6]
After mian.py file is run  for training to be completed, which file should be run for generating the output of the provided word list. In short, how to use save model variables for handwriting generation of specific words?

**Comment by Nikolai10** [comment]
Hello @DeccanKing1, 

I have added an example script - please have a look at src/run_inference.py.

After successfully running the script you should get something similar to:
![sample](https://user-images.githubusercontent.com/12114732/101630301-0198f580-3a23-11eb-8ea6-300f5fb265f8.png)

**Comment by DeccanKing1** [comment]
Thank you.
