### ISSUE TITLE
ValueError: tf.function-decorated function tried to create variables on non-first call.

### ISSUE THREAD

**Issue by layert** [Nikolai10/scrabble-gan#7]
hallo.

i trained the full featured scrabbleGAN (on Windows 7) to the end, but when the generator model is to be saved i get the following error: "ValueError: tf.function-decorated function tried to create variables on non-first call."

after that i haved trained the scrabbleGAN without the "NonLocalBlock" and everything worked well, so the problem is with the "NonLocalBlock".

can somebody help?

**Comment by superwhyun** [comment]
I have same problem. After training 15 epoch completed, it crashes on saving generator model.

**Comment by h3clikejava** [comment]
I have same problem.

**Comment by mohcib** [comment]
I have the same problem. I am working on a fix.

**Comment by Nikolai10** [comment]
@layert @superwhyun @h3clikejava @mohcib: please try to replace the NonLocalBlock with the new version: https://github.com/Nikolai10/scrabble-gan/commit/7ef4521f0a95cfd4090d208010b08784cd22e045.

This should resolve the issue.
