### ISSUE TITLE
changing shared_specs.kernel_reg = None.  and its effect on output

### ISSUE THREAD

**Issue by DeccanKing1** [Nikolai10/scrabble-gan#9]
I could only run the code when I updated shared_specs.kernel_reg = None. What effect does it have on the generated output?

**Comment by Nikolai10** [comment]
Hello @DeccanKing1, 

the idea was to use spectral normalization `shared_specs.kernel_reg = @spectral_norm`, which at the time of writing hasn't been yet available as an official TF feature. If you are planning to experiment with spectral norm in your project, I highly recommend using https://www.tensorflow.org/addons/api_docs/python/tfa/layers/SpectralNormalization. 

For more information on spectral norm, please have a look at https://arxiv.org/pdf/1705.10941.pdf.

**Comment by DeccanKing1** [comment]
Thank you for the explanation.
